[PSQP-2361] Implementação da tela Relatórios
Ranpu123/BudgetApp pull request #2
Opened 2024-06-24 18:05 UTC by Ranpu123

O que foi feito?

> A implementação de componentes de UI da tela de relatórios, bem como a lógica para listagem e remoção de transações. Foi implementada a navegação aninhada entre as telas da aplicação utilizando NavGraph. Foi adicionado filtros por valor e por data de inclusão para as transações.

Adicionar link da Task

> [PSQP-2361]

Impacto

> Médio

2024-06-25 16:48 UTC, andre-bahia requested changes

2024-06-25 16:48 UTC, andre-bahia commented on .idea/deploymentTargetSelector.xml
Ficou faltando colocar o diretorio inteiro no gitignore, ainda tá pegando arquivos ocultos

2024-06-25 16:48 UTC, andre-bahia commented on app/src/main/java/com/example/budgetapp/presentation/components/DoubleSwitch.kt
> +                    "Variáveis",
Não manjo muito ainda de Compose, mas já pensou em alguma estratégia de declaração de strings nos seus componentes de UI? E se precisarmos internacionalizar nosso app, como fariamos?
É só um questionamento para você pensar e estudar não precisa implementar agora

2024-06-25 16:48 UTC, andre-bahia commented on app/src/main/java/com/example/budgetapp/presentation/components/GenericDropMenu.kt
> +        /*OutlinedTextField(
Remover código comentado

2024-06-25 16:48 UTC, andre-bahia commented on app/src/main/java/com/example/budgetapp/presentation/components/TransactionDateHeader.kt
> +fun toFormattedDate(date: LocalDate): String{
Essa regra não daria para ficar no ViewModel?

2024-06-25 16:48 UTC, andre-bahia commented on app/src/main/java/com/example/budgetapp/presentation/views/HomeView.kt
> +@Preview(showBackground = true)
Remover código comentado

2024-06-25 16:49 UTC, andre-bahia commented
Tá ficando top seu app man, parabéns

2024-06-25 17:23 UTC, Ranpu123 commented on app/src/main/java/com/example/budgetapp/presentation/components/DoubleSwitch.kt
> +                    "Variáveis",
Ele usa o mesmo esquema do Strings.xml do View, vou dar uma olhada pra passar todas os textos do app pra ele.

2024-07-03 19:19 UTC, andre-bahia approved these changes

2024-07-03 19:22 UTC, merged