[PSQP-2428] Implementação de testes unitários
Ranpu123/BudgetApp pull request #5
Opened 2024-07-30 18:54 UTC by Ranpu123

O que foi feito?

> Foram implementados testes unitários para as camadas de apresentação e de dados, abrangendo as classes de ViewModel, repositório e utilitários. Também foram criados testes integrados para validação dos serviços de fundo para sincronização CoroutineWorkers.

Adicionar link da Task

> [PSQP-2428]

Impacto

> Baixo

<img src="https://github.com/user-attachments/assets/78deb199-aec1-4975-b7c7-ae7e094d277b" width=50% height=50%>

2024-07-30 18:56 UTC, Ranpu123 commented
@tqirqueiroz
@emersonsenaTQI
@andre-bahia
Poderiam revisar esse pull request por favor?

2024-07-31 12:27 UTC, tqirqueiroz requested changes
Os testes ficaram show de bola, muito bom trabalho. Apontei alguns pontos de atenção, ajustando isso fica top demais mano, parabens.

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/components/AddExpenseBottomSheet.kt
> +                        /*if(bottomSheetViewModel.validadeForm(description, currencyToDouble(value))){
Remover codigo comentado.

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/components/AddExpenseBottomSheet.kt
> +                              if(bottomSheetViewModel.checkForm()){
No padrão mvvm não é uma boa pratica fazer chamadas para o VM com retorno direto pra view, o ideal seria fazer as chamadas para o VM e observar um state com a "resposta" pra essa chamada, ou com o estado esperado da view pra essa chamada. Tenta alterar esse if pra chamar o checkForm, muda o state com o resultado e observa esse state e faz o if.

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/components/AddFExpenseBottomSheet.kt
> +                              if(bottomSheetViewModel.checkForm()){
mesma coisa!

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/components/AddFIncomeBottomSheet.kt
> +                              if(bottomSheetViewModel.checkForm()){
mesma coisa!

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/components/AddIncomeBottomSheet.kt
> +                              if(bottomSheetViewModel.checkForm()){
mesma coisa!

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/viewModels/home/HomeViewModel.kt
> +        //_uiState.value.copy(isLoading = true)
Codigo comentado

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/viewModels/transactionBottomSheet/ExpenseBottomSheetViewModel.kt
> +    fun checkForm(): Boolean {
Percebi essa função meio repetida em alguns lugares, poderia verificar pra extrair o que for comum entre os fluxos e deixar em um lugar comum(extension, ou utils ou outra coisa do tipo).

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/viewModels/transactionBottomSheet/FExpenseBottomSheetViewModel.kt
> +    fun checkForm(): Boolean {
aqui tbm

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/viewModels/transactionBottomSheet/FIncomeBottomSheetViewModel.kt
> +    fun checkForm(): Boolean {
aqui

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/presentation/viewModels/transactionBottomSheet/IncomeBottomSheetViewModel.kt
> +    fun checkForm(): Boolean {
aqui

2024-07-31 12:27 UTC, tqirqueiroz commented on app/src/main/java/com/example/budgetapp/utils/CurrencyToDouble.kt
> +        val cleanS = it.replace("[  $symbol,.\u00A0]".toRegex(), "")
esses caracteres podem ser uma constante

2024-07-31 17:57 UTC, Ranpu123 commented on app/src/main/java/com/example/budgetapp/utils/CurrencyToDouble.kt
> +        val cleanS = it.replace("[  $symbol,.\u00A0]".toRegex(), "")
[Arquivo de constantes adicionado](https://github.com/Ranpu123/BudgetApp/pull/5/commits/1a96c096aff296c926c8b5928eabc45a2b9238b7), estava precisando mesmo.

2024-07-31 18:01 UTC, Ranpu123 commented on app/src/main/java/com/example/budgetapp/presentation/components/AddExpenseBottomSheet.kt
> +                              if(bottomSheetViewModel.checkForm()){
Removi o if de dentro do onClick e criei um [variável do estado para manter a view atualizada](https://github.com/Ranpu123/BudgetApp/pull/5/commits/b37b7616de711e1b0735521f9bd415120db8d27a) se o valor foi incluído.

2024-07-31 18:08 UTC, merged